<?php

function has_seen_schema() {
  $schema['has_seen'] = array(
    
    // Example (partial) specification for table "node".
    'description' => 'The base table for the has seen module.',
    'fields' => array(
    	'nid' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
    	'uid' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
	),
  	'primary key' => array('nid', 'uid'),
  );
  return $schema;
}
